# Generated by Django 5.0.1 on 2024-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datos',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
